In [1]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import pandas as pd
import datetime as dt
from datetime import datetime
from scipy import stats


# Reflect Tables into SQLAlchemy ORM

In [3]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from sqlalchemy import inspect

In [4]:
# create engine to hawaii.sqlite
engine = create_engine("sqlite:///hawaii.sqlite")

In [5]:
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

/Users/sunitak/opt/anaconda3/envs/pythondata/lib/python3.7/site-packages/ipykernel_launcher.py:4: SADeprecationWarning: The AutomapBase.prepare.reflect parameter is deprecated and will be removed in a future release.  Reflection is enabled when AutomapBase.prepare.autoload_with is passed.
  after removing the cwd from sys.path.


In [6]:
# View all of the classes that automap found
Base.classes.keys()

['measurement', 'station']

In [7]:
# Save references to each table
measurement = Base.classes.measurement
station = Base.classes.station

In [8]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Precipitation Analysis

In [9]:
# Find the most recent date in the data set.
inspector = inspect(engine)
columns = inspector.get_columns('measurement')
for column in columns:
    print(column['name'], column["type"])

id INTEGER
station TEXT
date TEXT
prcp FLOAT
tobs FLOAT


In [10]:
measurement.results = session.query(measurement.date, measurement.prcp).all()
session.query(measurement.prcp).group_by(measurement.date).all()
measurement.results

[('2010-01-01', 0.08),
 ('2010-01-02', 0.0),
 ('2010-01-03', 0.0),
 ('2010-01-04', 0.0),
 ('2010-01-06', None),
 ('2010-01-07', 0.06),
 ('2010-01-08', 0.0),
 ('2010-01-09', 0.0),
 ('2010-01-10', 0.0),
 ('2010-01-11', 0.01),
 ('2010-01-12', 0.0),
 ('2010-01-14', 0.0),
 ('2010-01-15', 0.0),
 ('2010-01-16', 0.0),
 ('2010-01-17', 0.0),
 ('2010-01-18', 0.0),
 ('2010-01-19', 0.0),
 ('2010-01-20', 0.0),
 ('2010-01-21', 0.0),
 ('2010-01-22', 0.0),
 ('2010-01-23', 0.0),
 ('2010-01-24', 0.01),
 ('2010-01-25', 0.0),
 ('2010-01-26', 0.04),
 ('2010-01-27', 0.12),
 ('2010-01-28', 0.0),
 ('2010-01-30', None),
 ('2010-01-31', 0.03),
 ('2010-02-01', 0.01),
 ('2010-02-03', None),
 ('2010-02-04', 0.01),
 ('2010-02-05', 0.0),
 ('2010-02-06', 0.0),
 ('2010-02-07', 0.0),
 ('2010-02-08', 0.0),
 ('2010-02-09', 0.0),
 ('2010-02-11', 0.0),
 ('2010-02-12', 0.02),
 ('2010-02-13', 0.01),
 ('2010-02-14', 0.0),
 ('2010-02-15', 0.0),
 ('2010-02-16', 0.0),
 ('2010-02-17', 0.0),
 ('2010-02-19', None),
 ('2010-02-20', 0

In [11]:
# Find the most recent date in the data set.
latest_date = session.query(measurement.date).order_by(measurement.date.desc()).first()
latest_date

('2017-08-23',)

In [12]:
#Starting from the most recent data point in the database. 
#query for the last data format, from string to datetime format
lastdate = dt.datetime.strptime(latest_date[0],'%Y-%m-%d')

# Calculate the date 1 year ago from the last data point in the database
query_date = dt.date(lastdate.year - 1, lastdate.month, lastdate.day)
query_date

datetime.date(2016, 8, 23)

In [13]:
# Perform a query to retrieve the data and precipitation scores
session.query(measurement.prcp).group_by(measurement.date).all()
select = [measurement.date, measurement.prcp]
result = session.query(*select).filter(measurement.date >= query_date).all()
result

[('2016-08-23', 0.0),
 ('2016-08-24', 0.08),
 ('2016-08-25', 0.08),
 ('2016-08-26', 0.0),
 ('2016-08-27', 0.0),
 ('2016-08-28', 0.01),
 ('2016-08-29', 0.0),
 ('2016-08-30', 0.0),
 ('2016-08-31', 0.13),
 ('2016-09-01', 0.0),
 ('2016-09-02', 0.0),
 ('2016-09-03', 0.0),
 ('2016-09-04', 0.03),
 ('2016-09-05', None),
 ('2016-09-06', None),
 ('2016-09-07', 0.05),
 ('2016-09-08', 0.0),
 ('2016-09-09', 0.03),
 ('2016-09-10', 0.0),
 ('2016-09-11', 0.05),
 ('2016-09-12', 0.0),
 ('2016-09-13', 0.02),
 ('2016-09-14', 1.32),
 ('2016-09-15', 0.42),
 ('2016-09-16', 0.06),
 ('2016-09-17', 0.05),
 ('2016-09-18', 0.0),
 ('2016-09-19', 0.0),
 ('2016-09-20', 0.0),
 ('2016-09-21', 0.0),
 ('2016-09-22', 0.02),
 ('2016-09-23', 0.0),
 ('2016-09-24', 0.0),
 ('2016-09-25', 0.0),
 ('2016-09-26', 0.06),
 ('2016-09-27', 0.02),
 ('2016-09-28', 0.0),
 ('2016-09-29', 0.0),
 ('2016-09-30', 0.0),
 ('2016-10-01', 0.0),
 ('2016-10-02', 0.0),
 ('2016-10-03', 0.0),
 ('2016-10-04', 0.0),
 ('2016-10-05', 0.0),
 ('2016-10-06'

In [14]:
# Design a query to retrieve the last 12 months of precipitation data and plot the results. 

# Starting from the most recent data point in the database. 
results_date = session.query(measurement.date).order_by(measurement.date.desc()).first()

latest_date = dt.datetime.strptime("2017-8-23","%Y-%m-%d")

# Calculate the date one year from the last date in data set.
last_year = latest_date - dt.timedelta(days=365)


# Perform a query to retrieve the data and precipitation scores
ppt_results = session.query(measurement.date, measurement.prcp).order_by(measurement.date.asc()).\
        filter(measurement.date>=last_year).all()

# Save the query results as a Pandas DataFrame and set the index to the date column
ppt_results_df = pd.DataFrame(ppt_results, columns=['date','prcp'])
ppt_results_df = ppt_results_df.rename(columns={'prcp':'precipitation', 'date':'date'})


# Sort the dataframe by date
ppt_results_df.sort_values(by = ['date'], ascending=True)


date  precipitation
0     2016-08-24           0.08
1     2016-08-24           2.15
2     2016-08-24           2.28
3     2016-08-24            NaN
4     2016-08-24           1.22
...          ...            ...
2218  2017-08-22           0.50
2221  2017-08-23           0.08
2219  2017-08-23           0.00
2220  2017-08-23           0.00
2222  2017-08-23           0.45

[2223 rows x 2 columns]

In [15]:
#checking for the missing values
ppt_results_df.dropna().all

#setting date as index 
ppt_results_df = ppt_results_df.set_index('date')

In [32]:
#Plot the results by using the DataFrame plot method with date as the x and precipitation as the y variables
fig, ax = plt.subplots(figsize = (10, 8))
ppt_results_df.plot(ax = ax, x_compat = True, color='teal')

#plt.xlabel= ['date']
#plt.ylabel = ['precipitation']
#set title and labels
ax.set_xlabel('date')
ax.set_ylabel('Precipitation in inches')
ax.set_title("Hawaii Precipitation 2016-2017")

plt.savefig("Output_results/precip.png")

#plot figure
#plt.tight_layout()
plt.show()

In [17]:
# Use Pandas to calculate the summary statistics for the precipitation data
ppt_results_df.describe()

precipitation
count    2015.000000
mean        0.176462
std         0.460288
min         0.000000
25%         0.000000
50%         0.020000
75%         0.130000
max         6.700000

# Exploratory Station Analysis

In [18]:
# Design a query to calculate the total number stations in the dataset
columns2 = inspector.get_columns('station')
for column in columns2:
    print(column["name"], column["type"])

id INTEGER
station TEXT
name TEXT
latitude FLOAT
longitude FLOAT
elevation FLOAT


In [19]:
station_results = session.query(station.station, station.name, station.latitude, station.longitude, station.elevation).all()
station_results 

[('USC00519397', 'WAIKIKI 717.2, HI US', 21.2716, -157.8168, 3.0),
 ('USC00513117', 'KANEOHE 838.1, HI US', 21.4234, -157.8015, 14.6),
 ('USC00514830', 'KUALOA RANCH HEADQUARTERS 886.9, HI US', 21.5213, -157.8374, 7.0),
 ('USC00517948', 'PEARL CITY, HI US', 21.3934, -157.9751, 11.9),
 ('USC00518838', 'UPPER WAHIAWA 874.3, HI US', 21.4992, -158.0111, 306.6),
 ('USC00519523', 'WAIMANALO EXPERIMENTAL FARM, HI US', 21.33556, -157.71139, 19.5),
 ('USC00519281', 'WAIHEE 837.5, HI US', 21.45167, -157.84888999999998, 32.9),
 ('USC00511918', 'HONOLULU OBSERVATORY 702.2, HI US', 21.3152, -157.9992, 0.9),
 ('USC00516128', 'MANOA LYON ARBO 785.2, HI US', 21.3331, -157.8025, 152.4)]

In [20]:
# Design a query to find the most active stations (i.e. what stations have the most rows?)

#station count
station_count = session.query(station).group_by(station.station).count()
station_count

9

***No. of Station***
There are total 9 stations for taking the measurements of weather. 

In [21]:
# List the stations and the counts in descending order.
station_list = session.query(measurement.station, func.count(measurement.station)).group_by(measurement.station)\
                .order_by(func.count(measurement.station).desc()).all()
station_list

[('USC00519281', 2772),
 ('USC00519397', 2724),
 ('USC00513117', 2709),
 ('USC00519523', 2669),
 ('USC00516128', 2612),
 ('USC00514830', 2202),
 ('USC00511918', 1979),
 ('USC00517948', 1372),
 ('USC00518838', 511)]

***Station with maximum data record***
Station id 'USC00519281' ('WAIHEE 837.5, HI US', Lat:21.45167, Lon:-157.84888999999998, 32.9) has maximum data record and most active station.

In [22]:
# Using the most active station id from the previous query, calculate the lowest, highest, and average temperature.
active_station = 'USC00519281'

temp_record = session.query(func.min(measurement.tobs), func.max(measurement.tobs), func.avg(measurement.tobs))\
                .filter(measurement.station == active_station).all()

print(f"Lowest Temperature: {temp_record[0][0]} oF")
print(f"Highest Temperature: {temp_record[0][0]} oF")
print(f"Average Temperature: {temp_record[0][0]} oF")

Lowest Temperature: 54.0 oF
Highest Temperature: 54.0 oF
Average Temperature: 54.0 oF


In [23]:
# Using the most active station id
# Query the last 12 months of temperature observation data for this station and plot the results as a histogram
temp_column = [measurement.date, measurement.tobs]

temp_annual = session.query(*temp_column).filter(measurement.station == active_station).filter(measurement.date >= last_year).all()
temp_annual

[('2016-08-24', 77.0),
 ('2016-08-25', 80.0),
 ('2016-08-26', 80.0),
 ('2016-08-27', 75.0),
 ('2016-08-28', 73.0),
 ('2016-08-29', 78.0),
 ('2016-08-30', 77.0),
 ('2016-08-31', 78.0),
 ('2016-09-01', 80.0),
 ('2016-09-02', 80.0),
 ('2016-09-03', 78.0),
 ('2016-09-04', 78.0),
 ('2016-09-05', 78.0),
 ('2016-09-06', 73.0),
 ('2016-09-07', 74.0),
 ('2016-09-08', 80.0),
 ('2016-09-09', 79.0),
 ('2016-09-10', 77.0),
 ('2016-09-11', 80.0),
 ('2016-09-12', 76.0),
 ('2016-09-13', 79.0),
 ('2016-09-14', 75.0),
 ('2016-09-15', 79.0),
 ('2016-09-16', 78.0),
 ('2016-09-17', 79.0),
 ('2016-09-18', 78.0),
 ('2016-09-19', 78.0),
 ('2016-09-20', 76.0),
 ('2016-09-21', 74.0),
 ('2016-09-22', 77.0),
 ('2016-09-23', 78.0),
 ('2016-09-24', 79.0),
 ('2016-09-25', 79.0),
 ('2016-09-26', 77.0),
 ('2016-09-27', 80.0),
 ('2016-09-28', 78.0),
 ('2016-09-29', 78.0),
 ('2016-09-30', 78.0),
 ('2016-10-01', 77.0),
 ('2016-10-02', 79.0),
 ('2016-10-03', 79.0),
 ('2016-10-04', 79.0),
 ('2016-10-05', 79.0),
 ('2016-10-

In [24]:
#plot the temp_annual as a histogram

temp_annual_df = pd.DataFrame(temp_annual, columns =['date','tobs'])
temp_annual_df.head()


date  tobs
0  2016-08-24  77.0
1  2016-08-25  80.0
2  2016-08-26  80.0
3  2016-08-27  75.0
4  2016-08-28  73.0

In [33]:
fig, ax = plt.subplots(figsize = (10, 8))
temp_annual_df.hist(ax = ax, bins=12, alpha=0.7, color='teal')

#set title and labels
ax.set_xlabel('Temperature (oF)')
ax.set_ylabel('Frequency')
ax.set_title("Histogram Plot - Hawaii Temperature 2016-2017")

#save figure 
plt.savefig('Output_results/temp_histogram.png')



plt.show()

# Close session

In [27]:
# Close Session
session.close()